### ISSUE TITLE
run.py don't exist

### ISSUE THREAD

**Issue by dannyboyxx** [dory111111/Pengenuity#1]
poetry run python src/run.py (run.py) don't exist in repository, please support . thanks.

**Comment by dory111111** [comment]
Thank you for letting me know.
It was a typographical error in "src/main.py", and I have fixed it!

**Comment by dannyboyxx** [comment]
> Thank you for letting me know.
> It was a typographical error in "src/main.py", and I have fixed it!

**ok , but after first task, issue = Traceback (most recent call last):**

  File "/Users/agentx/Desktop/cartella senza nome/Pengenuity/src/main.py", line 61, in <module>
    agent.run()
  File "/Users/agentx/Desktop/cartella senza nome/Pengenuity/src/agent.py", line 134, in run
    self.save_agent()
  File "/Users/agentx/Desktop/cartella senza nome/Pengenuity/src/agent.py", line 267, in save_agent
    self.episodic_memory.save_local(path=episodic_memory_dir)
  File "/Users/agentx/Desktop/cartella senza nome/Pengenuity/src/memory/episodic_memory.py", line 105, in save_local
    self.vector_store.save_local(folder_path=path)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'save_local'

**Comment by dannyboyxx** [comment]
> > Thank you for letting me know.
> > It was a typographical error in "src/main.py", and I have fixed it!
> 
> **ok , but after first task, issue = Traceback (most recent call last):**
> 
> File "/Users/agentx/Desktop/cartella senza nome/Pengenuity/src/main.py", line 61, in agent.run() File "/Users/agentx/Desktop/cartella senza nome/Pengenuity/src/agent.py", line 134, in run self.save_agent() File "/Users/agentx/Desktop/cartella senza nome/Pengenuity/src/agent.py", line 267, in save_agent self.episodic_memory.save_local(path=episodic_memory_dir) File "/Users/agentx/Desktop/cartella senza nome/Pengenuity/src/memory/episodic_memory.py", line 105, in save_local self.vector_store.save_local(folder_path=path) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ AttributeError: 'NoneType' object has no attribute 'save_local'

**--------------------------------- -> I tried 3 more times, but this time it generated a new error**

Traceback (most recent call last):
  File "/Users/agentx/Desktop/cartella senza nome/Pengenuity/src/main.py", line 61, in <module>
    agent.run()
  File "/Users/agentx/Desktop/cartella senza nome/Pengenuity/src/agent.py", line 130, in run
    action_result = args["result"]
                    ~~~~^^^^^^^^^^
KeyError: 'result'

**Comment by dannyboyxx** [comment]
please support me

**Comment by dory111111** [comment]
Thank you for the report!
Is it possible to provide more details such as the conditions under which the error occurred?

Also, we plan to add logging functionality in the future to enable debugging. If logging is possible, it should help us analyze and resolve bugs.

**Comment by dannyboyxx** [comment]
the error occurs immediately after the first task, I would really like to use your agent, it seems to me more intelligent than the others

**Comment by dannyboyxx** [comment]
> the error occurs immediately after the first task, I would really like to use your agent, it seems to me more intelligent than the others

**if it helps i am running it on mac m1**
